### ISSUE TITLE
Linux dist error

### ISSUE THREAD

**Issue by pauf419** [AmberTeam/Cimber#1]
I get this error every time I try to scrape Kinogo: 

`
2022-12-18 17:13:24,816 ERROR LOGGER - System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List1.Enumerator.MoveNext()
   at Cimber.Scraper.Scrapers.KinogoScraper.getFilm(String url)
`

I'm running the code on Ubuntu 22.04.1.

**Comment by xndrpr** [comment]
Fixed!
